import Head from 'next/head';
import React, { useState } from 'react';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Next13 from '../components/Blog/Next13';


export default function Articles() {

    const [isDark, setIsDark] = useState(false);

    function setDark() {
        if (isDark === false) {
            setIsDark(true);
        } else {
            setIsDark(false);
        }
        console.log(isDark);
    }
    return (
        <div className={isDark ? 'dark' : ''}>

            <Head>
                <title>Articles</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/avatar.png" />
            </Head>
            <main className='w-full relative dark:bg-slate-900 transition-all ease-in duration-300'>
                <Navbar dark={isDark} darkFunc={setDark} />
                <Next13/>
                <Footer />
            </main>
        </div>
    );
}
