import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import React, { useState } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    const [isDark, setIsDark] = useState(false);

    function setDark(){
        if(isDark === false){
            setIsDark(true);
        }else{
            setIsDark(false);
        }
        console.log(isDark);
    }
    return (
        <>
            <div className={isDark ? 'dark' : ''}>

                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/images/avatar.png" />
                </Head>
                <main className='w-full relative scroll-smooth dark:bg-slate-700 transition-all ease-in duration-300 snap-y snap-proximity overflow-y-scroll h-screen'>
                    <Navbar dark={isDark} darkFunc={setDark}/>
                    <Header/>
                    <Footer/>
                </main>
            </div>
        </>
    );
}
